services:
  db:
    image: mysql
    container_name: bugtrack_db
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - data:/var/lib/mysql
    networks:
      - net
  
  api:
    container_name: bugtrack_api
    image: bugtrack/api
    env_file:
      - ./api/.env
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - net

  ui:
    container_name: bugtrack_ui
    image: bugtrack/ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - api
    networks:
      - net

volumes:
  data:

networks:
  net:

